      - name: Resize icon to all densities
        run: |
          mkdir -p app/src/main/res/mipmap-mdpi
          mkdir -p app/src/main/res/mipmap-hdpi
          mkdir -p app/src/main/res/mipmap-xhdpi
          mkdir -p app/src/main/res/mipmap-xxhdpi
          mkdir -p app/src/main/res/mipmap-xxxhdpi
          ls -la  # Esto muestra qué archivos hay en la raíz
          convert icon_original.png -resize 48x48 app/src/main/res/mipmap-mdpi/ic_launcher.png
          convert icon_original.png -resize 72x72 app/src/main/res/mipmap-hdpi/ic_launcher.png
          convert icon_original.png -resize 96x96 app/src/main/res/mipmap-xhdpi/ic_launcher.png
          convert icon_original.png -resize 144x144 app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          convert icon_original.png -resize 192x192 app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          
